<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Browse</name>
   <tag></tag>
   <elementGuidId>d48ef1ac-be1a-4c29-8a26-b0936db13ed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;coral-92&quot;]/div/div[1]/span[1]/span/span/button/i</value>
   </webElementProperties>
</WebElementEntity>
