<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>abd76236-064f-494f-b129-b88ed99f550e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cq-siteadmin-admin-actions-edit-activator foundation-collection-action coral-Button--graniteActionBar coral-Button coral-Button--quiet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-foundation-collection-action</name>
      <type>Main</type>
      <value>{&quot;target&quot;:&quot;.cq-siteadmin-admin-childpages&quot;,&quot;activeSelectionCount&quot;:&quot;multiple&quot;,&quot;action&quot;:&quot;cq.wcm.open&quot;,&quot;data&quot;:{&quot;cookiePath&quot;:&quot;/&quot;,&quot;href&quot;:&quot;/bin/wcmcommand?cmd=open&amp;_charset_=utf-8&amp;path={item}&quot;}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is</name>
      <type>Main</type>
      <value>coral-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>quiet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>M</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;skipCoral2Validation touch wf-adobeclean-i4-active wf-adobeclean-n3-active wf-adobeclean-n4-active wf-adobeclean-n7-active wf-adobecleancondensed-n4-active wf-adobecleancondensed-n7-active wf-active&quot;]/body[@class=&quot;coral--light shell-collectionpage-view&quot;]/div[@class=&quot;granite-collection-selectionbar foundation-mode-switcher&quot;]/div[@class=&quot;foundation-mode-switcher-item foundation-mode-switcher-item-active&quot;]/coral-actionbar[@class=&quot;granite-selectionbar foundation-collection-actionbar coral-ActionBar&quot;]/coral-actionbar-primary[@class=&quot;coral-ActionBar-primary&quot;]/coral-actionbar-item[@class=&quot;coral-ActionBar-item&quot;]/button[@class=&quot;cq-siteadmin-admin-actions-edit-activator foundation-collection-action coral-Button--graniteActionBar coral-Button coral-Button--quiet&quot;]</value>
   </webElementProperties>
</WebElementEntity>
