<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coral-columnview-item-thumbnai</name>
   <tag></tag>
   <elementGuidId>efc8fd21-69d1-40ad-bd50-afe3602579e7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>coral-columnview-item-thumbnail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral3-ColumnView-item-thumbnail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;granite-shell-content&quot;)/div[@class=&quot;foundation-layout-panel-bodywrapper&quot;]/div[@class=&quot;foundation-layout-panel-body&quot;]/div[@class=&quot;foundation-layout-panel-content&quot;]/coral-columnview[@class=&quot;cq-siteadmin-admin-childpages foundation-collection foundation-layout-columnview coral3-ColumnView coral3-ColumnView--selection&quot;]/coral-columnview-column[@class=&quot;coral3-ColumnView-column&quot;]/coral-columnview-column-content[@class=&quot;coral3-ColumnView-column-content&quot;]/coral-columnview-item[@class=&quot;foundation-collection-item coral3-ColumnView-item&quot;]/coral-columnview-item-thumbnail[@class=&quot;coral3-ColumnView-item-thumbnail&quot;]</value>
   </webElementProperties>
</WebElementEntity>
