<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JNCW</name>
   <tag></tag>
   <elementGuidId>d4ac056c-0a8a-45b9-8db5-ad538a5d0a10</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-ColumnView-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JNCW</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-header1519727536257-message&quot;)/div[@class=&quot;coral-Pathbrowser-pickerPanel&quot;]/div[@class=&quot;coral-ColumnView&quot;]/nav[@class=&quot;coral-ColumnView-column&quot;]/div[@class=&quot;coral-ColumnView-column-content&quot;]/a[@class=&quot;coral-ColumnView-item coral-ColumnView-item--hasChildren&quot;]/div[@class=&quot;coral-ColumnView-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
