<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_header-desktop-logo.png</name>
   <tag></tag>
   <elementGuidId>6bd924c6-117a-4f10-8efe-f0f6015ee0a8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-ColumnView-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>header-desktop-logo.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-header1519893431297-message&quot;)/div[@class=&quot;coral-Pathbrowser-pickerPanel&quot;]/div[@class=&quot;coral-ColumnView&quot;]/nav[@class=&quot;coral-ColumnView-column&quot;]/div[@class=&quot;coral-ColumnView-column-content&quot;]/a[@class=&quot;coral-ColumnView-item&quot;]/div[@class=&quot;coral-ColumnView-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
