<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dam</name>
   <tag></tag>
   <elementGuidId>b837f3f2-1491-4d55-94ee-b209b9ac9297</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coral-ColumnView-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dam</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-header1519893431297-message&quot;)/div[@class=&quot;coral-Pathbrowser-pickerPanel&quot;]/div[@class=&quot;coral-ColumnView&quot;]/nav[@class=&quot;coral-ColumnView-column&quot;]/div[@class=&quot;coral-ColumnView-column-content&quot;]/a[@class=&quot;coral-ColumnView-item coral-ColumnView-item--hasChildren&quot;]/div[@class=&quot;coral-ColumnView-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
